CREATE OR ALTER VIEW [dbo].[vServerTopQueriesStore]
AS
SELECT
	 [stqi].[ReportID]
	,[stqi].[CaptureDate]
	,[stqi].[ServerIdentifier]
	,[stqi].[Measurement]
	,[stqs].[DatabaseName]
	,[stqs].[PlanID]
	,[stqs].[QueryID]
	,[stqs].[QueryTextID]
	,[stqs].[ObjectID]
	,[stqs].[SchemaName]
	,[stqs].[ObjectName]
	,[stqs].[ExecutionTypeDesc]
	,[stqs].[ExecutionCount]
	,[stqs].[Duration]
	,[stqs].[CPU]
	,[stqs].[LogicalIOReads]
	,[stqs].[LogicalIOWrites]
	,[stqs].[PhysicalIOReads]
	,[stqs].[CLR]
	,[stqs].[Memory]
	,[stqs].[LogBytes]
	,[stqs].[TempDBSpace]
	,CAST(DECOMPRESS([stqs].[QuerySqlText]) AS NVARCHAR(MAX))	AS [QuerySqlText]
FROM [dbo].[vServerTopQueriesIndex] [stqi]
INNER JOIN [dbo].[ServerTopQueriesStore] [stqs]
ON [stqi].[ReportID] = [stqs].[ReportID]