CREATE OR ALTER VIEW [dbo].[vQDSCleanupIndex]
AS
SELECT
	 [ReportID]			
	,[ReportDate]		
	,[ServerIdentifier]	
	,[DatabaseName]		
	,[QueryType]			
	,[QueryCount]		
	,[PlanCount]			
	,[QueryTextKBs]		
	,[PlanXMLKBs]		
	,[RunStatsKBs]		
	,[WaitStatsKBs]		
	,[TestMode]	
	,[CleanupParameters].value('(/Root/CleanupParameters/CleanAdhocStale)[1]','BIT')	AS [CleanAdhocStale]
	,[CleanupParameters].value('(/Root/CleanupParameters/CleanStale)[1]','BIT')			AS [CleanStale]
	,[CleanupParameters].value('(/Root/CleanupParameters/Retention)[1]','BIT')			AS [Retention]
	,[CleanupParameters].value('(/Root/CleanupParameters/MinExecutionCount)[1]','BIT')	AS [MinExecutionCount]
	,[CleanupParameters].value('(/Root/CleanupParameters/CleanOrphan)[1]','BIT')		AS [CleanOrphan]
	,[CleanupParameters].value('(/Root/CleanupParameters/CleanInternal)[1]','BIT')		AS [CleanInternal]
FROM [dbo].[QDSCleanupIndex]