----------------------------------------------------------------------------------
-- View Name: [dbo].[vWaitsVariationStore]
--
-- Desc: This view is built on top of [dbo].[WaitsVariationStore] to extract the details generated by the executions of [dbo].[WaitsVariation]
--			Description of the wait categories can be found here:
--			https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-wait-stats-transact-sql?view=sql-server-ver15#wait-categories-mapping-table
--
-- Columns:
--		[ReportID]						BIGINT			NOT NULL
--			Unique Identifier for the execution (operations not logged to table have no ReportID)
--
--		[QueryID]						BIGINT			NOT NULL
--			Query Identifier of the query with a wait variation
--
--		[ObjectID]						BIGINT			NOT NULL
--			Object Identifier the [QueryID] is part of (if any)
--
--		[SchemaName]					SYSNAME				NULL
--			Name of the schema of the object the [QueryID] is part of (if any)
--
--		[ObjectName]					SYSNAME				NULL
--			Name of the object the [QueryID] is part of (if any)
--
--		[ExecutionCount_History]		DECIMAL(20,2)		NULL
--			Number of executions of the [QueryID] in the period of time identified as "History"
--
--		[ExecutionCount_Recent]			DECIMAL(20,2)		NULL
--			Number of executions of the [QueryID] in the period of time identified as "Recent"
--
--		[ExecutionCount_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the number of executions between the period of times identified as "History" and "Recent"
--
--		[Total_History]					DECIMAL(20,2)		NULL
--			Total wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Total_Recent]					DECIMAL(20,2)		NULL
--			Total wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Total_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the Total wait time between the period of times identified as "History" and "Recent"
--
--		[Unknown_History]				DECIMAL(20,2)		NULL
--			Total Unknown wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Unknown_Recent]				DECIMAL(20,2)		NULL
--			Total Unknown wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Unknown_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Unknown wait time between the period of times identified as "History" and "Recent"
--
--		[CPU_History]					DECIMAL(20,2)		NULL
--			Total CPU wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[CPU_Recent]					DECIMAL(20,2)		NULL
--			Total CPU wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[CPU_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the CPU wait time between the period of times identified as "History" and "Recent"
--
--		[WorkerThread_History]			DECIMAL(20,2)		NULL
--			 Worker Thread wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[WorkerThread_Recent]			DECIMAL(20,2)		NULL
--			Worker Thread wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[WorkerThread_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Worker Thread wait time between the period of times identified as "History" and "Recent"
--
--		[Lock_History]					DECIMAL(20,2)		NULL
--			Lock wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Lock_Recent]					DECIMAL(20,2)		NULL
--			Lock wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Lock_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the Lock wait time between the period of times identified as "History" and "Recent"
--
--		[Latch_History]					DECIMAL(20,2)		NULL
--			Latch wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Latch_Recent]					DECIMAL(20,2)		NULL
--			Latch wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Latch_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the Latch wait time between the period of times identified as "History" and "Recent"
--
--		[BufferLatch_History]			DECIMAL(20,2)		NULL
--			Buffer Latch wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[BufferLatch_Recent]			DECIMAL(20,2)		NULL
--			Buffer Latch wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[BufferLatch_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Buffer Latch wait time between the period of times identified as "History" and "Recent"
--
--		[BufferIO_History]				DECIMAL(20,2)		NULL
--			 Buffer IO wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[BufferIO_Recent]				DECIMAL(20,2)		NULL
--			Buffer IO wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[BufferIO_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Buffer IO wait time between the period of times identified as "History" and "Recent"
--
--		[Compilation_History]			DECIMAL(20,2)		NULL
--			Compilation wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Compilation_Recent]			DECIMAL(20,2)		NULL
--			Compilation wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Compilation_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Compilation wait time between the period of times identified as "History" and "Recent"
--
--		[SQLCLR_History]				DECIMAL(20,2)		NULL
--			SQL CLR wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[SQLCLR_Recent]					DECIMAL(20,2)		NULL
--			SQL CLR wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[SQLCLR_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the SQL CLR wait time between the period of times identified as "History" and "Recent"
--
--		[Mirroring_History]				DECIMAL(20,2)		NULL
--			Mirroring wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Mirroring_Recent]				DECIMAL(20,2)		NULL
--			Mirroring wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Mirroring_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Mirroring wait time between the period of times identified as "History" and "Recent"
--
--		[Transaction_History]			DECIMAL(20,2)		NULL
--			Transaction wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Transaction_Recent]			DECIMAL(20,2)		NULL
--			Transaction wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Transaction_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Transaction wait time between the period of times identified as "History" and "Recent"
--
--		[Idle_History]					DECIMAL(20,2)		NULL
--			Idle wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Idle_Recent]					DECIMAL(20,2)		NULL
--			Idle wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Idle_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the Idle wait time between the period of times identified as "History" and "Recent"
--
--		[Preemptive_History]			DECIMAL(20,2)		NULL
--			Preemptive wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Preemptive_Recent]				DECIMAL(20,2)		NULL
--			Preemptive wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Preemptive_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Preemptive wait time between the period of times identified as "History" and "Recent"
--
--		[ServiceBroker_History]			DECIMAL(20,2)		NULL
--			Service Broker wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[ServiceBroker_Recent]			DECIMAL(20,2)		NULL
--			Service Broker wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[ServiceBroker_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Service Broker wait time between the period of times identified as "History" and "Recent"
--
--		[TranLogIO_History]				DECIMAL(20,2)		NULL
--			Transaction LOG IO wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[TranLogIO_Recent]				DECIMAL(20,2)		NULL
--			Transaction Log IO wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[TranLogIO_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Transaction Log IO wait time between the period of times identified as "History" and "Recent"
--
--		[NetworkIO_History]				DECIMAL(20,2)		NULL
--			Network IO wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[NetworkIO_Recent]				DECIMAL(20,2)		NULL
--			Network IO wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[NetworkIO_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Network IO wait time between the period of times identified as "History" and "Recent"
--
--		[Parallelism_History]			DECIMAL(20,2)		NULL
--			Parallelism wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
---
--		[Parallelism_Recent]			DECIMAL(20,2)		NULL
--			Parallelism wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Parallelism_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Parallelism wait time between the period of times identified as "History" and "Recent"
--
--		[Memory_History]				DECIMAL(20,2)		NULL
--			Memory wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Memory_Recent]					DECIMAL(20,2)		NULL
--			Memory wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Memory_Variation%]				DECIMAL(20,2)		NULL
--			Variation (in %) in the Memory wait time between the period of times identified as "History" and "Recent"
--
--		[UserWait_History]				DECIMAL(20,2)		NULL
--			User wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[UserWait_Recent]				DECIMAL(20,2)		NULL
--			User wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[UserWait_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the User wait time between the period of times identified as "History" and "Recent"
--
--		[Tracing_History]				DECIMAL(20,2)		NULL
--			Tracing wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Tracing_Recent]				DECIMAL(20,2)		NULL
--			Tracing wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Tracing_Variation%]			DECIMAL(20,2)		NULL
--			Variation (in %) in the Tracing wait time between the period of times identified as "History" and "Recent"
--
--		[FullTextSearch_History]		DECIMAL(20,2)		NULL
--			FullTextSearch wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[FullTextSearch_Recent]			DECIMAL(20,2)		NULL
--			FullTextSearch wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[FullTextSearch_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the FullTextSearch wait time between the period of times identified as "History" and "Recent"
--
--		[OtherDiskIO_History]			DECIMAL(20,2)		NULL
--			Other Disk IO wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[OtherDiskIO_Recent]			DECIMAL(20,2)		NULL
--			Other Disk IO wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[OtherDiskIO_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Other Disk IO wait time between the period of times identified as "History" and "Recent"
--
--		[Replication_History]			DECIMAL(20,2)		NULL
--			Replication wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[Replication_Recent]			DECIMAL(20,2)		NULL
--			Replication wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[Replication_Variation%]		DECIMAL(20,2)		NULL
--			Variation (in %) in the Replication wait time between the period of times identified as "History" and "Recent"
--
--		[LogRateGovernor_History]		DECIMAL(20,2)		NULL
--			Log Rate Governor wait time of the [QueryID] in the period of time identified as "History" (in microseconds)
--
--		[LogRateGovernor_Recent]		DECIMAL(20,2)		NULL
--			Log Rate Governor wait time of the [QueryID] in the period of time identified as "Recent" (in microseconds)
--
--		[LogRateGovernor_Variation%]	DECIMAL(20,2)		NULL
--			Variation (in %) in the Log Rate Governor wait time between the period of times identified as "History" and "Recent"
--
--		[QuerySqlText]					NVARCHAR(MAX)	    NULL
--			Query text of the [QueryID]
--
-- Date: 2020.10.22
-- Auth: Pablo Lozano (@sqlozano)
--
-- Date: 2021.05.05
-- Auth: Pablo Lozano (@sqlozano)
--			Swapped the Recent/History columns so the metrics will be read from left to right "History / Recent / Variation"
----------------------------------------------------------------------------------

CREATE OR ALTER VIEW [dbo].[vWaitsVariationStore]
AS
SELECT
	 [wvi].[ReportID]
	,[wvs].[QueryID]
	,[wvs].[ObjectID]
	,[wvs].[SchemaName]
	,[wvs].[ObjectName]
	,[wvs].[ExecutionCount_History]		
	,[wvs].[ExecutionCount_Recent]		
	,[wvs].[ExecutionCount_Variation%]	
	,[wvs].[Total_History]				
	,[wvs].[Total_Recent]					
	,[wvs].[Total_Variation%]				
	,[wvs].[Unknown_History]				
	,[wvs].[Unknown_Recent]				
	,[wvs].[Unknown_Variation%]			
	,[wvs].[CPU_History]					
	,[wvs].[CPU_Recent]					
	,[wvs].[CPU_Variation%]				
	,[wvs].[WorkerThread_History]			
	,[wvs].[WorkerThread_Recent]			
	,[wvs].[WorkerThread_Variation%]		
	,[wvs].[Lock_History]					
	,[wvs].[Lock_Recent]					
	,[wvs].[Lock_Variation%]				
	,[wvs].[Latch_History]				
	,[wvs].[Latch_Recent]					
	,[wvs].[Latch_Variation%]				
	,[wvs].[BufferLatch_History]			
	,[wvs].[BufferLatch_Recent]			
	,[wvs].[BufferLatch_Variation%]		
	,[wvs].[BufferIO_History]				
	,[wvs].[BufferIO_Recent]				
	,[wvs].[BufferIO_Variation%]			
	,[wvs].[Compilation_History]			
	,[wvs].[Compilation_Recent]			
	,[wvs].[Compilation_Variation%]		
	,[wvs].[SQLCLR_History]				
	,[wvs].[SQLCLR_Recent]				
	,[wvs].[SQLCLR_Variation%]			
	,[wvs].[Mirroring_History]			
	,[wvs].[Mirroring_Recent]				
	,[wvs].[Mirroring_Variation%]			
	,[wvs].[Transaction_History]			
	,[wvs].[Transaction_Recent]			
	,[wvs].[Transaction_Variation%]		
	,[wvs].[Idle_History]					
	,[wvs].[Idle_Recent]					
	,[wvs].[Idle_Variation%]				
	,[wvs].[Preemptive_History]			
	,[wvs].[Preemptive_Recent]			
	,[wvs].[Preemptive_Variation%]		
	,[wvs].[ServiceBroker_History]		
	,[wvs].[ServiceBroker_Recent]			
	,[wvs].[ServiceBroker_Variation%]		
	,[wvs].[TranLogIO_History]			
	,[wvs].[TranLogIO_Recent]				
	,[wvs].[TranLogIO_Variation%]			
	,[wvs].[NetworkIO_History]			
	,[wvs].[NetworkIO_Recent]				
	,[wvs].[NetworkIO_Variation%]			
	,[wvs].[Parallelism_History]			
	,[wvs].[Parallelism_Recent]			
	,[wvs].[Parallelism_Variation%]		
	,[wvs].[Memory_History]				
	,[wvs].[Memory_Recent]				
	,[wvs].[Memory_Variation%]			
	,[wvs].[UserWait_History]				
	,[wvs].[UserWait_Recent]				
	,[wvs].[UserWait_Variation%]			
	,[wvs].[Tracing_History]				
	,[wvs].[Tracing_Recent]				
	,[wvs].[Tracing_Variation%]			
	,[wvs].[FullTextSearch_History]		
	,[wvs].[FullTextSearch_Recent]		
	,[wvs].[FullTextSearch_Variation%]	
	,[wvs].[OtherDiskIO_History]			
	,[wvs].[OtherDiskIO_Recent]			
	,[wvs].[OtherDiskIO_Variation%]		
	,[wvs].[Replication_History]			
	,[wvs].[Replication_Recent]			
	,[wvs].[Replication_Variation%]		
	,[wvs].[LogRateGovernor_History]		
	,[wvs].[LogRateGovernor_Recent]		
	,[wvs].[LogRateGovernor_Variation%]	
	,CAST(DECOMPRESS([wvs].[QueryText]) AS NVARCHAR(MAX))	AS [QueryText]
FROM [dbo].[WaitsVariationStore] [wvs]
INNER JOIN [dbo].[vWaitsVariationIndex] [wvi]
ON [wvs].[ReportID] = [wvi].[ReportID]
