----------------------------------------------------------------------------------
-- Table Name: [dbo].[PlanMiner_MissingIndexes]
--
-- Desc: This table contains all the details of the indexes the SQL engine consideres could improve its performance
--
-- Columns:
--		[PlanMinerID]			BIGINT			NOT NULL
--			Unique identifier of the mined plan
--
--		[StatementID]			INT				NOT NULL
--			Identifier of the statement the missing index was identified for
--
--		[MissingIndexID]		INT				NOT NULL
--			Identifier of the missing index (generated by SQL Engine itself)
--
--		[Impact]				FLOAT			NULL
--			Estimated impact of the missing index
--
--		[DatabaseNamePlan]		NVARCHAR(128)	NULL
--			Name of the database where the index should be created
--
--		[SchemaName]			NVARCHAR(128)	NULL
--			Name of the schema where the index should be created
--
--		[TableName]				NVARCHAR(128)	NULL
--			Name of the table where the index should be created
--
--		[Usage]					NVARCHAR(128)	NULL
--
--
--		[ColumnName]			NVARCHAR(128)	NULL
--			Name of the column to be included in the index
--
-- Notes:
--		When using table variables or temp tables, [SchemaName] and [TableName] will contain NULL values
--
-- Date: 2021.05.07
-- Auth: Pablo Lozano (@sqlozano)
--
----------------------------------------------------------------------------------

DROP TABLE IF EXISTS [dbo].[PlanMiner_MissingIndexes]
CREATE TABLE [dbo].[PlanMiner_MissingIndexes]
(
	 [PlanMinerID]		BIGINT			NOT NULL
	,[StatementID]		INT				NOT NULL
	,[MissingIndexID]	INT				NOT NULL
	,[Impact]			FLOAT			NULL
	,[DatabaseNamePlan]	NVARCHAR(128)	NULL
	,[SchemaName]		NVARCHAR(128)	NULL
	,[TableName]		NVARCHAR(128)	NULL
	,[Usage]			NVARCHAR(128)	NULL
	,[ColumnName]		NVARCHAR(128)	NULL
)
CREATE CLUSTERED INDEX [CIX_PlanMiner_MissingIndexes] ON [dbo].[PlanMiner_MissingIndexes]
(
	 [PlanMinerID]		ASC
	,[StatementID]		ASC
	,[MissingIndexID]	ASC
)
