----------------------------------------------------------------------------------
-- Table Name: [dbo].[PlanMiner_MissingIndexes]
--
-- Desc: This table contains all the details of the indexes the SQL engine consideres could improve its performance
--
-- Columns:
--		[ServerIdentifier]		SYSNAME			NOT NULL
--			Identifier of the server, so if this data is centralized reports originated on each server can be properly identified
--
--		[DatabaseName]			SYSNAME			NOT NULL
--			Name of the database this plan's information has been mined out
--
--		[PlanID]				BIGINT			NOT NULL
--			Identifier of the plan this information has been mined out
--			
--		[MissingIndexID]		INT				NOT NULL
--			Identifier of the missing index (generated by SQL Engine itself)
--
--		[Impact]				FLOAT			NULL
--			Estimated impact of the missing index
--
--		[DatabaseNamePlan]		NVARCHAR(128)	NULL
--			Name of the database where the index should be created
--
--		[SchemaName]			NVARCHAR(128)	NULL
--			Name of the schema where the index should be created
--
--		[TableName]				NVARCHAR(128)	NULL
--			Name of the table where the index should be created
--
--		[Usage]					NVARCHAR(128)	NULL
--
--
--		[ColumnName]			NVARCHAR(128)	NULL
--			Name of the column to be included in the index
--
-- Notes:
--		When using table variables or temp tables, [SchemaName] and [TableName] will contain NULL values
--
-- Date: 2021.mm.dd
-- Auth: Pablo Lozano (@sqlozano)
--
----------------------------------------------------------------------------------

DROP TABLE IF EXISTS [dbo].[PlanMiner_MissingIndexes]
CREATE TABLE [dbo].[PlanMiner_MissingIndexes]
(
	 [ServerIdentifier]	SYSNAME			NOT NULL
	,[DatabaseName]		SYSNAME			NOT NULL
	,[PlanID]			BIGINT			NOT NULL
	,[MissingIndexID]	INT				NOT NULL
	,[Impact]			FLOAT			NULL
	,[DatabaseNamePlan]	NVARCHAR(128)	NULL
	,[SchemaName]		NVARCHAR(128)	NULL
	,[TableName]		NVARCHAR(128)	NULL
	,[Usage]			NVARCHAR(128)	NULL
	,[ColumnName]		NVARCHAR(128)	NULL
)
CREATE CLUSTERED INDEX [CIX_PlanMiner_MissingIndexes] ON [dbo].[PlanMiner_MissingIndexes]
(
	 [ServerIdentifier]	ASC
	,[DatabaseName]		ASC
	,[PlanID]			ASC
	,[MissingIndexID]	ASC
)
